# Generated by Django 3.2.6 on 2021-09-22 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wish',
            name='listing_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='wish',
            name='user',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
